### ISSUE TITLE
Database error with Drupal 7.76+

### ISSUE THREAD

**Issue by niels-heinemann** [CiviMRF/cmrf_core#51] opened 2021-06-29 20:43 UTC
Dear folks,

I get following error in latest webform on latest drupal 7 and latest civicrm when calling the civiMRF tab i webform edit:

`PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'cmrf_core_call`` (status, connector_id, request, metadata, request_hash, create_' at line 1: INSERT INTO {`cmrf_core_call`} (status, connector_id, request, metadata, request_hash, create_date, scheduled_date) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4, :db_insert_placeholder_5, :db_insert_placeholder_6); Array ( [:db_insert_placeholder_0] => INIT [:db_insert_placeholder_1] => urn:cmrf:connector:cmrf_form_processor_connector:dad65ff5460f58d [:db_insert_placeholder_2] => {"entity":"FormProcessorInstance","action":"list","options":[]} [:db_insert_placeholder_3] => {"callbacks":null,"cache":"180 minutes"} [:db_insert_placeholder_4] => 2cd0ad39b29c32c9bbefbd7735f1cebcf1b8a48d [:db_insert_placeholder_5] => 2021-06-29 22:41:22 [:db_insert_placeholder_6] => ) in CMRF\Drupal\SQLPersistingCallFactory->createOrFetch() (Zeile 144 von [...]/sites/all/modules/cmrf_core-7.x-0.13/CMRF_Drupal/SQLPersistingCallFactory.php).`

Any educated guesses?

**Comment by jensschuppe** [comment] 2021-06-30 10:58
- Are there pending database updates (run `drush updb` oder visit `/update.php`)?
- Is the CMRFAbstractCore library up-to-date (run `composer update` inside the module directory)?
- Does clearing caches help?

**Comment by niels-heinemann** [comment] 2021-06-30 11:29
I'm afraid I have checked this all before and rechecked now. None helps.

**Comment by niels-heinemann** [comment] 2021-06-30 20:21
Does this module require a minimum mysql/mariadb version`?

**Comment by jensschuppe** [comment] 2021-07-01 07:53
> Does this module require a minimum mysql/mariadb version`?

Pinging @jaapjansma for the question about the dbs system version

@nielosz Can you provide detailed instructions on how to reproduce this on a clean install of Drupal 7?

**Comment by jaapjansma** [comment] 2021-07-01 08:05
I have never came across this error. I have installed this module on different servers/setups so my assumption is that it does work with all mysql/mariadb versions. 

Looking at your query there seems some weird replacement of 

```

insert into cmrf_core_call`` ...

```

There are two `` after the table name. I dont have a clue on how those got there.

**Comment by niels-heinemann** [comment] 2021-07-01 18:42
Jesses, thx for the hint. If I change[ line 9](https://github.com/CiviMRF/cmrf_core/blob/a1a9cd49e9f1ffa6a962d80d0c3bf44583e9248e/CMRF_Drupal/Core.php#L25) in `CMRF\Drupal\AbstractCore` from
`$table_name = \Database::getConnection()->prefixTables("{cmrf_core_call}");`
to
`$table_name = \Database::getConnection()->prefixTables("cmrf_core_call");`
i.e. if I remove the curly braces, it seems to work. 

Did you mean to interpolate s/th in there?

**Comment by jensschuppe** [comment] 2021-07-02 08:01
This replacement doesn't seem correct to me, since `prefixTables()` is supposed to strip those `{` and `}` from the table name. I still can't reproduce the error.

Also, the code path doesn't seem to be entered at all when opening the _CiviMRF_ tab on a webform during my testing. @nielosz Can you provide a full backtrace of the error? Please insert it here enclosed with triple backticks in order for the GitHub editor not messing with the formatting, see [here](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#fenced-code-blocks).

**Comment by niels-heinemann** [comment] 2021-07-02 08:16
Thanks Jens, do you have an idea how to produce such a backtrace? I tried with devel module without success.

**Comment by jensschuppe** [comment] 2021-07-02 08:27
@nielosz The Devel module provides krumo error handlers with backtraces, see [this stackexchange post](https://drupal.stackexchange.com/a/86751).

**Comment by niels-heinemann** [comment] 2021-07-02 08:34
Thats what I did, tried any combinations. No more output :/

**Comment by niels-heinemann** [comment] 2021-07-06 08:06
Don't I get any stacktrace because the error is catched?

**Comment by jensschuppe** [comment] 2021-07-06 12:55
If the error appears in the UI/the watchdog, it is not being caught.

Since we can't reproduce the error, I'm afraid we can't really help with this for now. Sorry for that.

You can try debugging the error yourself or re-install the module from scratch (and possibly compare what's different). Don't forget to backup!

**Comment by jensschuppe** [comment] 2021-07-15 11:25
I finally could reproduce the error with an updated Drupal 7 (7.76+) which introduced MySQL 8 support by escaping MySQL identifiers differently, which makes this (unnecessary) statement in the Drupal CiviMRF Core constructor cause a corrupt table name:

https://github.com/CiviMRF/cmrf_core/blob/a1a9cd49e9f1ffa6a962d80d0c3bf44583e9248e/CMRF_Drupal/Core.php#L25

There is no need for calling the table name prefix here, because it is being done later by Drupal itself, when using the database abstraction layer, which the module seems to be doing consistently.

@nielosz Could you try with deecb4d9e482641ce79dfe7430819f18c6265465 in branch `issue/51` whether this solves the problem and does not cause other malfunctions?

@jaapjansma I'd like you to have a look at this, too, since this made CiviMRF not work at all with Drupal 7.76+.

**Comment by jensschuppe** [comment] 2021-07-15 11:45
This might apply to MySQL 8 only - I could not reproduce with other versions or MariaDB. @nielosz Can you confirm that you're having the issue with MySQL 8?

**Comment by niels-heinemann** [comment] 2021-07-15 11:59
@jensschuppe, thx for your deep investigation. I'm afraid we got stuck with an old 
`mysqld  Ver 5.7.33-0ubuntu0.16.04.1 for Linux on x86_64 ((Ubuntu))`

**Comment by niels-heinemann** [comment] 2021-07-15 12:00
I'll try your fix.

**Comment by jaapjansma** [comment] 2021-07-15 12:03
Looks good to me!

**Comment by niels-heinemann** [comment] 2021-07-15 12:09
Seems to work. Thx

**Comment by jensschuppe** [comment] 2021-07-16 10:59
Thanks @jaapjansma and @nielosz for your test feedback, I merged the change, so this will be fixed with the next release.

**Closed as completed by jensschuppe** 2021-07-16 10:59 UTC
Labels: bug, 7.x
